server:
  port: 8080

spring:
  mvc:
    dispatch-options-request: true

  datasource:
    url: jdbc:mysql://localhost:3306/final_quiz?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true